// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/pb/raft.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that the generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion3

// RequestVoteRequest 请求投票请求
type RequestVoteRequest struct {
	// 候选人的任期号
	Term int64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// 候选人 ID
	CandidateId int64 `protobuf:"varint,2,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	// 候选人最后日志条目的索引
	LastLogIndex int64 `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	// 候选人最后日志条目的任期号
	LastLogTerm          int64    `protobuf:"varint,4,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteRequest) Reset()         { *m = RequestVoteRequest{} }
func (m *RequestVoteRequest) String() string { return proto.CompactTextString(m) }
func (*RequestVoteRequest) ProtoMessage()    {}

func (m *RequestVoteRequest) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteRequest) GetCandidateId() int64 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

func (m *RequestVoteRequest) GetLastLogIndex() int64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteRequest) GetLastLogTerm() int64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

// RequestVoteResponse 请求投票响应
type RequestVoteResponse struct {
	// 当前任期号，用于候选人更新自己
	Term int64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// 候选人获得投票
	Granted              bool     `protobuf:"varint,2,opt,name=granted,proto3" json:"granted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteResponse) Reset()         { *m = RequestVoteResponse{} }
func (m *RequestVoteResponse) String() string { return proto.CompactTextString(m) }
func (*RequestVoteResponse) ProtoMessage()    {}

func (m *RequestVoteResponse) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteResponse) GetGranted() bool {
	if m != nil {
		return m.Granted
	}
	return false
}

// AppendEntriesRequest 追加日志请求（也用作心跳）
type AppendEntriesRequest struct {
	// 领导者的任期号
	Term int64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// 领导者 ID
	LeaderId int64 `protobuf:"varint,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	// 新日志条目前一个条目的索引
	PrevLogIndex int64 `protobuf:"varint,3,opt,name=prevLogIndex,proto3" json:"prevLogIndex,omitempty"`
	// 新日志条目前一个条目的任期号
	PrevLogTerm int64 `protobuf:"varint,4,opt,name=prevLogTerm,proto3" json:"prevLogTerm,omitempty"`
	// 要存储的日志条目（心跳时为空）
	Entries []*LogEntry `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	// 领导者的 commitIndex
	LeaderCommit         int64    `protobuf:"varint,6,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesRequest) Reset()         { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()    {}

func (m *AppendEntriesRequest) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRequest) GetLeaderId() int64 {
	if m != nil {
		return m.LeaderId
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogIndex() int64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogTerm() int64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesRequest) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AppendEntriesRequest) GetLeaderCommit() int64 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

// AppendEntriesResponse 追加日志响应
type AppendEntriesResponse struct {
	// 当前任期号，用于领导者更新自己
	Term int64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// 如果跟随者包含匹配 prevLogIndex 和 prevLogTerm 的条目则为 true
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// 冲突条目的索引（用于快速回退）
	ConflictIndex int64 `protobuf:"varint,3,opt,name=conflictIndex,proto3" json:"conflictIndex,omitempty"`
	// 冲突条目的任期号
	ConflictTerm         int64    `protobuf:"varint,4,opt,name=conflictTerm,proto3" json:"conflictTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesResponse) Reset()         { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()    {}

func (m *AppendEntriesResponse) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AppendEntriesResponse) GetConflictIndex() int64 {
	if m != nil {
		return m.ConflictIndex
	}
	return 0
}

func (m *AppendEntriesResponse) GetConflictTerm() int64 {
	if m != nil {
		return m.ConflictTerm
	}
	return 0
}

// LogEntry 日志条目
type LogEntry struct {
	// 条目创建时的任期号
	Term int64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// 条目的索引
	Index int64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// 状态机要执行的命令
	Command              []byte   `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}

func (m *LogEntry) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *LogEntry) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *LogEntry) GetCommand() []byte {
	if m != nil {
		return m.Command
	}
	return nil
}

// InstallSnapshotRequest 安装快照请求
type InstallSnapshotRequest struct {
	// 领导者的任期号
	Term int64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// 领导者 ID
	LeaderId int64 `protobuf:"varint,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	// 快照最后包含的日志索引
	LastIncludedIndex int64 `protobuf:"varint,3,opt,name=lastIncludedIndex,proto3" json:"lastIncludedIndex,omitempty"`
	// 快照最后包含的日志任期
	LastIncludedTerm int64 `protobuf:"varint,4,opt,name=lastIncludedTerm,proto3" json:"lastIncludedTerm,omitempty"`
	// 快照数据
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallSnapshotRequest) Reset()         { *m = InstallSnapshotRequest{} }
func (m *InstallSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*InstallSnapshotRequest) ProtoMessage()    {}

func (m *InstallSnapshotRequest) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *InstallSnapshotRequest) GetLeaderId() int64 {
	if m != nil {
		return m.LeaderId
	}
	return 0
}

func (m *InstallSnapshotRequest) GetLastIncludedIndex() int64 {
	if m != nil {
		return m.LastIncludedIndex
	}
	return 0
}

func (m *InstallSnapshotRequest) GetLastIncludedTerm() int64 {
	if m != nil {
		return m.LastIncludedTerm
	}
	return 0
}

func (m *InstallSnapshotRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// InstallSnapshotResponse 安装快照响应
type InstallSnapshotResponse struct {
	// 当前任期号
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallSnapshotResponse) Reset()         { *m = InstallSnapshotResponse{} }
func (m *InstallSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*InstallSnapshotResponse) ProtoMessage()    {}

func (m *InstallSnapshotResponse) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestVoteRequest)(nil), "raft.RequestVoteRequest")
	proto.RegisterType((*RequestVoteResponse)(nil), "raft.RequestVoteResponse")
	proto.RegisterType((*AppendEntriesRequest)(nil), "raft.AppendEntriesRequest")
	proto.RegisterType((*AppendEntriesResponse)(nil), "raft.AppendEntriesResponse")
	proto.RegisterType((*LogEntry)(nil), "raft.LogEntry")
	proto.RegisterType((*InstallSnapshotRequest)(nil), "raft.InstallSnapshotRequest")
	proto.RegisterType((*InstallSnapshotResponse)(nil), "raft.InstallSnapshotResponse")
}
