// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/rpc.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// RpcRequest RPC 请求消息
type RpcRequest struct {
	ServiceName        string   `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MethodName         string   `protobuf:"bytes,2,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	Args               []byte   `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
RequestId            string   `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcRequest) Reset()         { *m = RpcRequest{} }
func (m *RpcRequest) String() string { return proto.CompactTextString(m) }
func (m *RpcRequest) ProtoMessage()  {}

func (m *RpcRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *RpcRequest) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *RpcRequest) GetArgs() []byte {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *RpcRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

// RpcResponse RPC 响应消息
type RpcResponse struct {
RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Result               []byte   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcResponse) Reset()         { *m = RpcResponse{} }
func (m *RpcResponse) String() string { return proto.CompactTextString(m) }
func (m *RpcResponse) ProtoMessage()  {}

func (m *RpcResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *RpcResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *RpcResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*RpcRequest)(nil), "proto.RpcRequest")
	proto.RegisterType((*RpcResponse)(nil), "proto.RpcResponse")
}
