/**
 * @file i2c.h
 * @brief I2C (Inter-Integrated Circuit) Driver
 *
 * I2C is a synchronous serial protocol developed by Philips (now NXP).
 * It uses only 2 signal lines for multi-master, multi-slave communication:
 *
 * - SDA (Serial Data): Bidirectional data line
 * - SCL (Serial Clock): Clock generated by the active master
 *
 * Key Concepts:
 *
 * 1. Multi-master, multi-slave bus:
 *    - Multiple masters can share the bus
 *    - Each slave has a unique 7-bit or 10-bit address
 *    - Open-drain outputs with pull-up resistors
 *
 * 2. Open-drain bus:
 *    - Devices can pull SDA/SCL LOW but cannot drive them HIGH
 *    - External pull-up resistors bring lines HIGH when idle
 *    - Wired-AND behavior: any LOW overrides all HIGHs
 *
 * 3. Protocol timing:
 *    - START condition: SDA goes LOW while SCL is HIGH
 *    - STOP condition: SDA goes HIGH while SCL is HIGH
 *    - Data valid: SDA must be stable while SCL is HIGH
 *    - Each byte must be followed by ACK/NACK bit
 *
 * 4. Data format per transaction:
 *    START + (SLAVE_ADDR + R/W) + ACK + DATA + ACK + ... + STOP
 *
 * 5. I2C Speed Modes:
 *    - Standard: 100 kHz
 *    - Fast: 400 kHz
 *    - Fast Plus: 1 MHz
 *    - High Speed: 3.4 MHz
 *
 * Timing diagram:
 *   SCL:  ___|‾‾‾‾|___|‾‾‾‾|___|‾‾‾‾|___|‾‾‾‾|___|‾‾‾‾|___
 *   SDA:  ‾‾‾‾‾‾‾‾‾|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|‾‾‾‾‾‾‾‾‾‾‾‾‾|______
 *              START  ADDR+R/W   ACK    DATA    ACK   STOP
 *
 * 6. ACK/NACK mechanism:
 *    - ACK: Receiver pulls SDA LOW during 9th clock pulse
 *    - NACK: Receiver leaves SDA HIGH during 9th clock pulse
 *    - Used for flow control and error detection
 */

#ifndef I2C_H
#define I2C_H

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

/* ==================== Configuration ==================== */

/** Maximum I2C clock frequency (Hz) */
#define I2C_MAX_CLOCK_FREQ 3400000   /**< 3.4 MHz (High Speed mode) */

/** Default I2C clock frequency */
#define I2C_DEFAULT_CLOCK 100000     /**< 100 kHz (Standard mode) */

/** Fast mode frequency */
#define I2C_FAST_MODE_CLOCK 400000   /**< 400 kHz */

/** Maximum I2C address (7-bit) */
#define I2C_MAX_ADDRESS 0x7F

/** I2C bus timeout in microseconds */
#define I2C_TIMEOUT_US 10000

/** Maximum I2C instances */
#define I2C_MAX_INSTANCES 4

/* ==================== I2C Speed Mode ==================== */

/** I2C speed mode configuration */
typedef enum {
    I2C_SPEED_STANDARD  = 100000,   /**< 100 kHz, standard mode */
    I2C_SPEED_FAST      = 400000,   /**< 400 kHz, fast mode */
    I2C_SPEED_FAST_PLUS = 1000000,  /**< 1 MHz, fast plus mode */
    I2C_SPEED_HIGH      = 3400000   /**< 3.4 MHz, high speed mode */
} i2c_speed_t;

/* ==================== I2C Addressing ==================== */

/** I2C address size (7-bit vs 10-bit addressing) */
typedef enum {
    I2C_ADDR_7BIT = 7,  /**< 7-bit address (most common, 128 addresses) */
    I2C_ADDR_10BIT = 10 /**< 10-bit address (1024 addresses) */
} i2c_addr_size_t;

/* ==================== I2C Operation Types ==================== */

/**
 * I2C transaction types for different communication patterns.
 * Each transaction has specific start/stop/ACK requirements.
 */
typedef enum {
    I2C_OP_WRITE = 0,   /**< Write to slave (R/W bit = 0) */
    I2C_OP_READ  = 1,   /**< Read from slave (R/W bit = 1) */
    I2C_OP_STOP  = 2,   /**< Generate STOP condition */
    I2C_OP_RESTART = 3  /**< Generate repeated START (no STOP) */
} i2c_op_t;

/* ==================== Error Types ==================== */

/** I2C error flags for detecting bus issues */
typedef enum {
    I2C_ERROR_NONE        = 0,   /**< No error */
    I2C_ERROR_NACK        = 1 << 0,  /**< No ACK from slave (address not found) */
    I2C_ERROR_ARBITRATION = 1 << 1,  /**< Lost arbitration (multi-master collision) */
    I2C_ERROR_TIMEOUT     = 1 << 2,  /**< Bus timeout (slave not responding) */
    I2C_ERROR_BUS_FAULT   = 1 << 3,  /**< Bus fault (SDA/SCL mismatch) */
    I2C_ERROR_OVERFLOW    = 1 << 4,  /**< RX buffer overflow */
    I2C_ERROR_DATA        = 1 << 5   /**< Invalid data length */
} i2c_error_t;

/* ==================== Callback Types ==================== */

/** TX complete callback function type */
typedef void (*i2c_tx_callback_t)(void *context);

/** RX complete callback function type */
typedef void (*i2c_rx_callback_t)(void *context, const uint8_t *data, size_t length);

/** Error callback function type */
typedef void (*i2c_error_callback_t)(void *context, i2c_error_t error);

/* ==================== DMA Transfer ==================== */

/** DMA transfer mode for high-speed I2C data movement */
typedef enum {
    I2C_DMA_OFF    = 0,  /**< No DMA, use polling/interrupts */
    I2C_DMA_TX_ONLY,     /**< DMA for TX, interrupts for RX */
    I2C_DMA_RX_ONLY,     /**< Interrupts for TX, DMA for RX */
    I2C_DMA_FULL         /**< DMA for both TX and RX */
} i2c_dma_mode_t;

/** DMA descriptor for I2C transfers */
typedef struct {
    uint8_t *buffer;      /**< Data buffer for DMA transfer */
    size_t   length;      /**< Number of bytes to transfer via DMA */
    size_t   transferred; /**< Bytes actually transferred */
    bool     circular;    /**< Circular buffer mode */
} i2c_dma_desc_t;

/* ==================== I2C Transaction ==================== */

/**
 * I2C transaction descriptor.
 * Defines a complete I2C communication sequence including
 * address, operations, and data buffers.
 */
typedef struct {
    uint16_t  address;        /**< Slave address (7-bit or 10-bit) */
    i2c_addr_size_t addr_size; /**< Address size */
    i2c_op_t *ops;            /**< Array of operations (start, write, read, stop) */
    uint8_t   num_ops;        /**< Number of operations */
    const uint8_t *tx_data;   /**< TX data buffer */
    uint8_t   *rx_data;       /**< RX data buffer */
    size_t    tx_len;         /**< TX data length */
    size_t    rx_len;         /**< RX data length */
} i2c_transaction_t;

/* ==================== I2C Instance State ==================== */

/** Complete I2C driver state structure */
typedef struct {
    /* Hardware configuration */
    uint8_t   instance;           /**< I2C instance number */
    uint32_t  base_addr;          /**< Memory-mapped I/O base address */
    uint32_t  clock_freq;         /**< Current SCL frequency in Hz */
    i2c_speed_t speed;            /**< I2C speed mode */
    i2c_addr_size_t addr_size;    /**< Address size (7-bit or 10-bit) */

    /* Bus state */
    bool bus_busy;            /**< Current bus busy state */
    bool bus_master;          /**< Current master mode */
    uint8_t own_address;      /**< I2C address of this device */
    bool ack_enabled;         /**< Auto-ACK mode enabled */

    /* FIFO buffers */
    uint8_t  tx_fifo[256];        /**< TX FIFO buffer */
    uint8_t  rx_fifo[256];        /**< RX FIFO buffer */
    size_t   tx_head;             /**< TX write pointer */
    size_t   tx_tail;             /**< TX read pointer */
    size_t   tx_count;            /**< Bytes in TX FIFO */
    size_t   rx_head;             /**< RX write pointer */
    size_t   rx_tail;             /**< RX read pointer */
    size_t   rx_count;            /**< Bytes in RX FIFO */

    /* DMA configuration */
    i2c_dma_mode_t dma_mode;      /**< DMA transfer mode */
    i2c_dma_desc_t dma_tx;        /**< TX DMA descriptor */
    i2c_dma_desc_t dma_rx;        /**< RX DMA descriptor */

    /* Interrupt configuration */
    bool irq_tx_enabled;          /**< TX interrupt enabled */
    bool irq_rx_enabled;          /**< RX interrupt enabled */
    bool irq_error_enabled;       /**< Error interrupt enabled */

    /* Callbacks */
    void *tx_context;             /**< User context for TX callback */
    i2c_tx_callback_t tx_cb;      /**< TX complete callback */
    void *rx_context;             /**< User context for RX callback */
    i2c_rx_callback_t rx_cb;      /**< RX complete callback */
    void *error_context;          /**< User context for error callback */
    i2c_error_callback_t error_cb; /**< Error callback */

    /* Status and error tracking */
    i2c_error_t errors;           /**< Accumulated error flags */
    bool enabled;                 /**< I2C peripheral enabled */
    bool busy;                    /**< Transfer in progress */
} i2c_t;

/* ==================== Public API ==================== */

/**
 * Initialize an I2C instance with specified configuration.
 *
 * Sets up speed mode, addressing, and enables the peripheral.
 *
 * @param i2c       Pointer to I2C structure
 * @param instance  I2C instance number
 * @param speed     I2C speed mode
 * @param addr_size Address size (7-bit or 10-bit)
 * @return true on success
 */
bool i2c_init(i2c_t *i2c, uint8_t instance, i2c_speed_t speed,
              i2c_addr_size_t addr_size);

/**
 * Enable or disable the I2C peripheral.
 *
 * @param i2c   Pointer to I2C instance
 * @param enable true to enable, false to disable
 */
void i2c_enable(i2c_t *i2c, bool enable);

/**
 * Set the I2C clock frequency (SCL frequency).
 *
 * @param i2c       Pointer to I2C instance
 * @param clock_freq Desired frequency in Hz
 * @return true on success
 */
bool i2c_set_clock(i2c_t *i2c, uint32_t clock_freq);

/**
 * Set the I2C address size (7-bit or 10-bit).
 *
 * @param i2c       Pointer to I2C instance
 * @param addr_size Address size
 */
void i2c_set_addr_size(i2c_t *i2c, i2c_addr_size_t addr_size);

/**
 * Set the own I2C address (for slave mode operation).
 *
 * When this device acts as a slave, it must have an address
 * that matches the master's addressing.
 *
 * @param i2c       Pointer to I2C instance
 * @param address   I2C address
 */
void i2c_set_own_address(i2c_t *i2c, uint8_t address);

/**
 * Generate a START condition on the I2C bus.
 *
 * START: SDA transitions HIGH → LOW while SCL is HIGH.
 * This signals the start of a new I2C transaction.
 *
 * @param i2c   Pointer to I2C instance
 * @return true on success
 */
bool i2c_start(i2c_t *i2c);

/**
 * Generate a STOP condition on the I2C bus.
 *
 * STOP: SDA transitions LOW → HIGH while SCL is HIGH.
 * This signals the end of an I2C transaction.
 *
 * @param i2c   Pointer to I2C instance
 * @return true on success
 */
bool i2c_stop(i2c_t *i2c);

/**
 * Generate a repeated START condition.
 *
 * Repeated START: SDA transitions HIGH → LOW while SCL is HIGH,
 * without a STOP in between. Used for changing direction
 * (read → write) without releasing the bus.
 *
 * @param i2c   Pointer to I2C instance
 * @return true on success
 */
bool i2c_restart(i2c_t *i2c);

/**
 * Write a byte to the I2C bus.
 *
 * @param i2c   Pointer to I2C instance
 * @param byte  Byte to transmit
 * @return true if ACK received, false if NACK
 */
bool i2c_write_byte(i2c_t *i2c, uint8_t byte);

/**
 * Read a byte from the I2C bus.
 *
 * @param i2c       Pointer to I2C instance
 * @param ack       true = send ACK, false = send NACK (last byte)
 * @return Received byte
 */
uint8_t i2c_read_byte(i2c_t *i2c, bool ack);

/**
 * Write data to an I2C slave device.
 *
 * Transaction: START + ADDR+W + ACK + DATA + ACK + ... + STOP
 *
 * @param i2c       Pointer to I2C instance
 * @param address   Slave address
 * @param data      Data buffer to write
 * @param length    Number of bytes
 * @return true on success
 */
bool i2c_write(i2c_t *i2c, uint16_t address, const uint8_t *data,
               size_t length);

/**
 * Read data from an I2C slave device.
 *
 * Transaction: START + ADDR+R + ACK + DATA(NACK) + STOP
 *
 * @param i2c       Pointer to I2C instance
 * @param address   Slave address
 * @param buf       Buffer to receive data into
 * @param length    Number of bytes
 * @return true on success
 */
bool i2c_read(i2c_t *i2c, uint16_t address, uint8_t *buf, size_t length);

/**
 * Combined write-then-read (common for register reads).
 *
 * Transaction: START + ADDR+W + ACK + REG_ADDR + ACK + RESTART
 *             + ADDR+R + ACK + DATA(NACK) + STOP
 *
 * This is the most common I2C pattern for reading registers.
 *
 * @param i2c       Pointer to I2C instance
 * @param address   Slave address
 * @param tx_data   Register/address to read from
 * @param tx_len    TX data length (usually 1 for register address)
 * @param rx_data   Buffer for received data
 * @param rx_len    RX data length
 * @return true on success
 */
bool i2c_write_read(i2c_t *i2c, uint16_t address,
                    const uint8_t *tx_data, size_t tx_len,
                    uint8_t *rx_data, size_t rx_len);

/**
 * Execute a full I2C transaction descriptor.
 *
 * @param i2c       Pointer to I2C instance
 * @param txn       Transaction descriptor
 * @return true on success
 */
bool i2c_transfer(i2c_t *i2c, i2c_transaction_t *txn);

/**
 * Blocking transfer with timeout.
 *
 * @param i2c       Pointer to I2C instance
 * @param address   Slave address
 * @param tx_data   TX data buffer
 * @param tx_len    TX length
 * @param rx_data   RX data buffer
 * @param rx_len    RX length
 * @param timeout_us Timeout in microseconds
 * @return true on success
 */
bool i2c_transfer_blocking(i2c_t *i2c, uint16_t address,
                           const uint8_t *tx_data, size_t tx_len,
                           uint8_t *rx_data, size_t rx_len,
                           uint32_t timeout_us);

/**
 * Configure DMA transfer mode.
 *
 * @param i2c   Pointer to I2C instance
 * @param mode  DMA mode
 */
void i2c_set_dma_mode(i2c_t *i2c, i2c_dma_mode_t mode);

/**
 * Enable or disable I2C interrupts.
 *
 * @param i2c       Pointer to I2C instance
 * @param irq_type  Which interrupt (TX, RX, error)
 * @param enable    true to enable, false to disable
 */
void i2c_enable_irq(i2c_t *i2c, uint8_t irq_type, bool enable);

/**
 * Register TX complete callback.
 *
 * @param i2c   Pointer to I2C instance
 * @param cb    Callback function
 * @param context User context pointer
 */
void i2c_set_tx_callback(i2c_t *i2c, i2c_tx_callback_t cb, void *context);

/**
 * Register RX complete callback.
 *
 * @param i2c   Pointer to I2C instance
 * @param cb    Callback function
 * @param context User context pointer
 */
void i2c_set_rx_callback(i2c_t *i2c, i2c_rx_callback_t cb, void *context);

/**
 * Register error callback.
 *
 * @param i2c   Pointer to I2C instance
 * @param cb    Callback function
 * @param context User context pointer
 */
void i2c_set_error_callback(i2c_t *i2c, i2c_error_callback_t cb, void *context);

/**
 * Clear accumulated error flags.
 *
 * @param i2c   Pointer to I2C instance
 */
void i2c_clear_errors(i2c_t *i2c);

/**
 * Get accumulated error flags.
 *
 * @param i2c   Pointer to I2C instance
 * @return Error flag bitmap
 */
i2c_error_t i2c_get_errors(i2c_t *i2c);

/**
 * Scan the I2C bus for connected devices.
 *
 * Sends a START + address byte to each possible address.
 * Devices that ACK are considered "present" on the bus.
 *
 * @param i2c       Pointer to I2C instance
 * @param addresses Output array to store found addresses
 * @param max_count Maximum number of addresses to find
 * @return Number of devices found
 */
int i2c_scan(i2c_t *i2c, uint16_t *addresses, int max_count);

/**
 * Simulate I2C bus acknowledgment (for testing).
 *
 * @param i2c   Pointer to I2C instance
 * @param ack   true = ACK, false = NACK
 */
void i2c_acknowledge(i2c_t *i2c, bool ack);

#endif /* I2C_H */
