/**
 * @file spi.h
 * @brief SPI (Serial Peripheral Interface) Driver
 *
 * SPI is a synchronous serial communication protocol developed by Motorola.
 * It uses a master-slave architecture with 4 signal lines:
 *
 * - SCLK (Serial Clock): Generated by master, clocks data bits
 * - MOSI (Master Out Slave In): Master transmits to slave
 * - MISO (Master In Slave Out): Slave transmits to master
 * - SS/CS (Slave Select/Chip Select): Active-low, selects target slave
 *
 * Key Concepts:
 *
 * 1. Clock Polarity (CPOL): State of SCLK when idle
 *    - CPOL=0: Idle = LOW,  data sampled on rising edge
 *    - CPOL=1: Idle = HIGH, data sampled on falling edge
 *
 * 2. Clock Phase (CPHA): When data is sampled relative to clock edge
 *    - CPHA=0: Data sampled on first edge, set on next edge
 *    - CPHA=1: Data sampled on second edge, set on next edge
 *
 * 3. SPI Modes (CPOL, CPHA):
 *    - Mode 0 (0,0): Idle LOW, sample rising edge (most common)
 *    - Mode 1 (0,1): Idle LOW, sample falling edge
 *    - Mode 2 (1,0): Idle HIGH, sample falling edge
 *    - Mode 3 (1,1): Idle HIGH, sample rising edge
 *
 * 4. Bit Order: MSB first (default) or LSB first
 *
 * Timing diagram (Mode 0, MSB first):
 *   SCLK:  ___|‾‾‾‾|___|‾‾‾‾|___|‾‾‾‾|___|‾‾‾‾|___
 *   MOSI:  0000000011111111 (MSB first)
 *   CS:    ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
 *
 * SPI is full-duplex: data is shifted out and in simultaneously.
 * Each clock cycle transfers 1 bit in each direction.
 */

#ifndef SPI_H
#define SPI_H

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

/* ==================== Configuration ==================== */

/** Maximum SPI clock frequency (Hz) */
#define SPI_MAX_CLOCK_FREQ 50000000  /**< 50 MHz max for modern devices */

/** Minimum SPI clock frequency (Hz) */
#define SPI_MIN_CLOCK_FREQ 100       /**< 100 kHz minimum */

/** Default SPI clock frequency */
#define SPI_DEFAULT_CLOCK 1000000    /**< 1 MHz default */

/** Maximum SPI bus width (bits per transfer) */
#define SPI_MAX_BUS_WIDTH 32

/** Maximum number of SPI instances */
#define SPI_MAX_INSTANCES 4

/* ==================== SPI Clock Mode ==================== */

/**
 * SPI clock polarity and phase configuration.
 * These must match between master and slave devices.
 */
typedef enum {
    SPI_MODE_0 = 0,  /**< CPOL=0, CPHA=0: Idle LOW, sample on rising edge (most common) */
    SPI_MODE_1 = 1,  /**< CPOL=0, CPHA=1: Idle LOW, sample on falling edge */
    SPI_MODE_2 = 2,  /**< CPOL=1, CPHA=0: Idle HIGH, sample on falling edge */
    SPI_MODE_3 = 3   /**< CPOL=1, CPHA=1: Idle HIGH, sample on rising edge */
} spi_mode_t;

/* ==================== Bit Order ==================== */

/** Bit transmission order for SPI data frames */
typedef enum {
    SPI_MSB_FIRST = 0,  /**< Most significant bit transmitted first (default) */
    SPI_LSB_FIRST = 1   /**< Least significant bit transmitted first */
} spi_bit_order_t;

/* ==================== Bus Width ==================== */

/** Data bus width for SPI transfers */
typedef enum {
    SPI_BUS_WIDTH_8  = 8,   /**< 8-bit transfers (most common) */
    SPI_BUS_WIDTH_16 = 16,  /**< 16-bit transfers (float, color values) */
    SPI_BUS_WIDTH_32 = 32   /**< 32-bit transfers (large registers) */
} spi_bus_width_t;

/* ==================== Error Types ==================== */

/** SPI error flags for detecting communication issues */
typedef enum {
    SPI_ERROR_NONE       = 0,   /**< No error */
    SPI_ERROR_OVERFLOW   = 1 << 0,  /**< RX overflow (slave didn't respond) */
    SPI_ERROR_MODE_FAULT = 1 << 1,  /**< Invalid slave selected */
    SPI_ERROR_TIMEOUT    = 1 << 2,  /**< Transfer timed out */
    SPI_ERROR_CRC        = 1 << 3,  /**< CRC check failed */
    SPI_ERROR_BUS_FAULT  = 1 << 4   /**< Bus collision or fault */
} spi_error_t;

/* ==================== Callback Types ==================== */

/** TX complete callback function type */
typedef void (*spi_tx_callback_t)(void *context, const uint8_t *data, size_t length);

/** RX complete callback function type */
typedef void (*spi_rx_callback_t)(void *context, const uint8_t *data, size_t length);

/** Error callback function type */
typedef void (*spi_error_callback_t)(void *context, spi_error_t error);

/* ==================== DMA Transfer ==================== */

/** DMA transfer mode for high-speed SPI data movement */
typedef enum {
    SPI_DMA_OFF    = 0,  /**< No DMA, use polling/interrupts */
    SPI_DMA_TX_ONLY,     /**< DMA for TX, interrupts for RX */
    SPI_DMA_RX_ONLY,     /**< Interrupts for TX, DMA for RX */
    SPI_DMA_FULL         /**< DMA for both TX and RX */
} spi_dma_mode_t;

/** DMA descriptor for SPI transfers */
typedef struct {
    uint8_t *buffer;      /**< Data buffer for DMA transfer */
    size_t   length;      /**< Number of bytes to transfer via DMA */
    size_t   transferred; /**< Bytes actually transferred */
    bool     circular;    /**< Circular buffer mode */
} spi_dma_desc_t;

/* ==================== Slave Select ==================== */

/**
 * Slave select configuration for multi-device SPI bus.
 * Each slave on the bus has a unique CS pin.
 */
typedef struct {
    uint8_t  pin;         /**< GPIO pin number for CS */
    bool     active_low;  /**< true = CS is active LOW (most common) */
    uint32_t delay_us;    /**< Delay after CS assertion (us) for setup time */
} spi_slave_select_t;

/* ==================== SPI Instance State ==================== */

/** Complete SPI driver state structure */
typedef struct {
    /* Hardware configuration */
    uint8_t   instance;           /**< SPI instance number */
    uint32_t  base_addr;          /**< Memory-mapped I/O base address */
    uint32_t  clock_freq;         /**< Current SCLK frequency in Hz */
    spi_mode_t mode;              /**< Clock polarity and phase */
    spi_bit_order_t bit_order;    /**< MSB or LSB first */
    spi_bus_width_t bus_width;    /**< Data bus width */

    /* Slave select */
    spi_slave_select_t slave_select; /**< CS/SS configuration */
    bool     cs_asserted;         /**< Current CS state */

    /* FIFO buffers for TX/RX data */
    uint8_t  tx_fifo[256];        /**< TX FIFO buffer */
    uint8_t  rx_fifo[256];        /**< RX FIFO buffer */
    size_t   tx_head;             /**< TX write pointer */
    size_t   tx_tail;             /**< TX read pointer */
    size_t   tx_count;            /**< Bytes in TX FIFO */
    size_t   rx_head;             /**< RX write pointer */
    size_t   rx_tail;             /**< RX read pointer */
    size_t   rx_count;            /**< Bytes in RX FIFO */

    /* DMA configuration */
    spi_dma_mode_t dma_mode;      /**< DMA transfer mode */
    spi_dma_desc_t dma_tx;        /**< TX DMA descriptor */
    spi_dma_desc_t dma_rx;        /**< RX DMA descriptor */

    /* Interrupt configuration */
    bool irq_tx_enabled;          /**< TX interrupt enabled */
    bool irq_rx_enabled;          /**< RX interrupt enabled */
    bool irq_error_enabled;       /**< Error interrupt enabled */

    /* Callbacks */
    void *tx_context;             /**< User context for TX callback */
    spi_tx_callback_t tx_cb;      /**< TX complete callback */
    void *rx_context;             /**< User context for RX callback */
    spi_rx_callback_t rx_cb;      /**< RX complete callback */
    void *error_context;          /**< User context for error callback */
    spi_error_callback_t error_cb; /**< Error callback */

    /* Status and error tracking */
    spi_error_t errors;           /**< Accumulated error flags */
    bool enabled;                 /**< SPI peripheral enabled */
    bool busy;                    /**< Transfer in progress */
} spi_t;

/* ==================== Public API ==================== */

/**
 * Initialize an SPI instance with specified configuration.
 *
 * Sets up clock polarity, phase, frequency, and bus width.
 * Both master and slave must agree on the SPI mode.
 *
 * @param spi       Pointer to SPI structure
 * @param instance  SPI instance number
 * @param clock_freq SCLK frequency in Hz
 * @param mode      SPI clock mode (CPOL, CPHA)
 * @param bit_order Bit transmission order
 * @param bus_width Data bus width
 * @return true on success
 */
bool spi_init(spi_t *spi, uint8_t instance, uint32_t clock_freq,
              spi_mode_t mode, spi_bit_order_t bit_order,
              spi_bus_width_t bus_width);

/**
 * Enable or disable the SPI peripheral.
 *
 * @param spi   Pointer to SPI instance
 * @param enable true to enable, false to disable
 */
void spi_enable(spi_t *spi, bool enable);

/**
 * Set the SPI clock frequency.
 *
 * The actual frequency may be rounded down to the nearest
 * divider of the system clock. Check spi_get_actual_clock()
 * for the real value.
 *
 * @param spi       Pointer to SPI instance
 * @param clock_freq Desired frequency in Hz
 * @return true on success
 */
bool spi_set_clock(spi_t *spi, uint32_t clock_freq);

/**
 * Configure slave select (chip select) pin.
 *
 * In a multi-device SPI bus, CS selects which slave receives
 * the data. CS is typically active-low.
 *
 * @param spi       Pointer to SPI instance
 * @param pin       GPIO pin number for CS
 * @param active_low true = CS active LOW
 * @param delay_us  Delay after CS assertion (setup time)
 */
void spi_set_slave_select(spi_t *spi, uint8_t pin, bool active_low,
                          uint32_t delay_us);

/**
 * Assert (lower) the chip select line.
 *
 * Must be called before data transfer to select the target slave.
 *
 * @param spi   Pointer to SPI instance
 */
void spi_cs_assert(spi_t *spi);

/**
 * Deassert (raise) the chip select line.
 *
 * Must be called after data transfer to deselect the slave.
 *
 * @param spi   Pointer to SPI instance
 */
void spi_cs_deassert(spi_t *spi);

/**
 * Write data to SPI (transmit only, no receive).
 *
 * SPI is full-duplex, so even "write" operations generate
 * dummy bytes on the MISO line. Use spi_transfer() for
 * simultaneous read/write.
 *
 * @param spi   Pointer to SPI instance
 * @param data  Data buffer to transmit
 * @param length Number of bytes
 * @return true on success
 */
bool spi_write(spi_t *spi, const uint8_t *data, size_t length);

/**
 * Read data from SPI (transmit dummy bytes to clock in data).
 *
 * SPI is full-duplex: to read, you must also send data
 * (typically zeros) to generate the clock signal.
 *
 * @param spi   Pointer to SPI instance
 * @param buf   Buffer to receive data into
 * @param length Number of bytes
 * @return true on success
 */
bool spi_read(spi_t *spi, uint8_t *buf, size_t length);

/**
 * Full-duplex SPI transfer (simultaneous read and write).
 *
 * For each byte sent, a byte is received simultaneously.
 * This is the core SPI operation.
 *
 * @param spi   Pointer to SPI instance
 * @param tx_buf Transmit buffer (can be NULL for read-only)
 * @param rx_buf Receive buffer (can be NULL for write-only)
 * @param length Number of bytes
 * @return true on success
 */
bool spi_transfer(spi_t *spi, const uint8_t *tx_buf, uint8_t *rx_buf,
                  size_t length);

/**
 * Blocking transfer with timeout.
 *
 * @param spi       Pointer to SPI instance
 * @param tx_buf    Transmit buffer
 * @param rx_buf    Receive buffer
 * @param length    Number of bytes
 * @param timeout_ms Timeout in milliseconds
 * @return true if transfer completed before timeout
 */
bool spi_transfer_blocking(spi_t *spi, const uint8_t *tx_buf,
                           uint8_t *rx_buf, size_t length,
                           uint32_t timeout_ms);

/**
 * Configure DMA transfer mode.
 *
 * @param spi   Pointer to SPI instance
 * @param mode  DMA mode
 */
void spi_set_dma_mode(spi_t *spi, spi_dma_mode_t mode);

/**
 * Enable or disable SPI interrupts.
 *
 * @param spi       Pointer to SPI instance
 * @param irq_type  Which interrupt (TX, RX, error)
 * @param enable    true to enable, false to disable
 */
void spi_enable_irq(spi_t *spi, uint8_t irq_type, bool enable);

/**
 * Register TX complete callback.
 *
 * @param spi   Pointer to SPI instance
 * @param cb    Callback function
 * @param context User context pointer
 */
void spi_set_tx_callback(spi_t *spi, spi_tx_callback_t cb, void *context);

/**
 * Register RX complete callback.
 *
 * @param spi   Pointer to SPI instance
 * @param cb    Callback function
 * @param context User context pointer
 */
void spi_set_rx_callback(spi_t *spi, spi_rx_callback_t cb, void *context);

/**
 * Register error callback.
 *
 * @param spi   Pointer to SPI instance
 * @param cb    Callback function
 * @param context User context pointer
 */
void spi_set_error_callback(spi_t *spi, spi_error_callback_t cb, void *context);

/**
 * Clear accumulated error flags.
 *
 * @param spi   Pointer to SPI instance
 */
void spi_clear_errors(spi_t *spi);

/**
 * Get accumulated error flags.
 *
 * @param spi   Pointer to SPI instance
 * @return Error flag bitmap
 */
spi_error_t spi_get_errors(spi_t *spi);

/**
 * Get actual (rounded) clock frequency.
 *
 * Due to clock divider limitations, the actual frequency
 * may differ from the requested frequency.
 *
 * @param spi   Pointer to SPI instance
 * @return Actual clock frequency in Hz
 */
uint32_t spi_get_actual_clock(spi_t *spi);

/**
 * Simulate SPI data reception (for testing).
 *
 * @param spi   Pointer to SPI instance
 * @param byte  Received byte
 */
void spi_rx_byte(spi_t *spi, uint8_t byte);

/**
 * Simulate SPI data transmission (for testing).
 *
 * @param spi   Pointer to SPI instance
 */
void spi_tx_byte_done(spi_t *spi);

#endif /* SPI_H */
