/**
 * @file spi.c
 * @brief SPI (Serial Peripheral Interface) Driver Implementation
 *
 * This file implements the SPI driver with:
 * - Master mode operation
 * - Clock polarity/phase (CPOL/CPHA) configuration
 * - MSB/LSB bit order
 * - Chip select management
 * - Full-duplex data transfer
 * - DMA transfer support
 *
 * SPI Protocol Theory:
 *
 * SPI uses a synchronous serial protocol with 4 wires:
 *
 * SCLK (Serial Clock):
 *   - Generated by the master device
 *   - Clock speed can range from kHz to MHz
 *   - Each clock pulse transfers 1 bit in each direction
 *
 * MOSI (Master Out → Slave In):
 *   - Master transmits data to slave on this line
 *   - Data changes on clock edge, sampled on opposite edge
 *
 * MISO (Master In ← Slave Out):
 *   - Slave transmits data to master on this line
 *   - Simultaneous with MOSI (full-duplex)
 *
 * SS/CS (Slave Select / Chip Select):
 *   - Active-low signal to select a specific slave
 *   - Only one slave can be selected at a time
 *   - Must be asserted before data transfer, deasserted after
 *
 * SPI Transfer Process:
 *   1. Master asserts CS (pulls LOW) to select slave
 *   2. Master generates clock pulses on SCLK
 *   3. On each clock edge, 1 bit is shifted on MOSI and MISO
 *   4. Master deasserts CS (pulls HIGH) to deselect slave
 *
 * Example: Transferring 0x5A (01011010) MSB first, Mode 0:
 *
 *   CS:   ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
 *   SCLK: ___|‾‾‾‾|___|‾‾‾‾|___|‾‾‾‾|___|‾‾‾‾|___|‾‾‾‾|___|‾‾‾‾|___|‾‾‾‾|___
 *   MOSI: 0       1     0     1     1     0     1     0
 *   MISO: x       y7    y6    y5    y4    y3    y2    y1
 *
 *   Where x = don't care (initial), y1-y8 = slave response bits
 *
 * Clock Polarity (CPOL) and Phase (CPHA):
 *
 *   Mode | CPOL | CPHA | SCLK Idle | Data Sampled On
 *   -----|------|------|-----------|------------------
 *   0    |  0   |  0   | LOW       | Rising edge (first)
 *   1    |  0   |  1   | LOW       | Falling edge (first)
 *   2    |  1   |  0   | HIGH      | Falling edge (first)
 *   3    |  1   |  1   | HIGH      | Rising edge (first)
 *
 * Mode 0 is the most common (idle LOW, sample on rising edge).
 * Both master and slave must use the same mode.
 *
 * Full-duplex nature:
 *   SPI transfers are simultaneous in both directions.
 *   Even a "write only" operation requires the slave to send
 *   dummy bytes to clock the data out. The master must read
 *   and discard these bytes.
 */

#include "spi.h"
#include <string.h>

/* ==================== Internal Helper Functions ==================== */

/**
 * Push a byte to the TX FIFO.
 */
static bool spi_fifo_push(spi_t *spi, uint8_t byte)
{
    if (spi->tx_count >= sizeof(spi->tx_fifo)) {
        return false;
    }

    spi->tx_fifo[spi->tx_head] = byte;
    spi->tx_head = (spi->tx_head + 1) % sizeof(spi->tx_fifo);
    spi->tx_count++;

    return true;
}

/**
 * Pop a byte from the RX FIFO.
 */
static bool spi_fifo_pop(spi_t *spi, uint8_t *byte)
{
    if (spi->rx_count == 0) {
        return false;
    }

    *byte = spi->rx_fifo[spi->rx_tail];
    spi->rx_tail = (spi->rx_tail + 1) % sizeof(spi->rx_fifo);
    spi->rx_count--;

    return true;
}

/**
 * Round clock frequency to nearest supported divider.
 *
 * In real hardware, SPI clock is derived from a system clock
 * using integer dividers. The actual frequency may differ.
 */
static uint32_t spi_round_clock(spi_t *spi, uint32_t target)
{
    /* Clamp to valid range */
    if (target > SPI_MAX_CLOCK_FREQ) {
        target = SPI_MAX_CLOCK_FREQ;
    }
    if (target < SPI_MIN_CLOCK_FREQ) {
        target = SPI_MIN_CLOCK_FREQ;
    }

    /* Simulate clock divider rounding (real hardware would use specific dividers) */
    /* For this educational implementation, we return the target as-is */
    (void)spi;
    return target;
}

/* ==================== Public API Implementation ==================== */

bool spi_init(spi_t *spi, uint8_t instance, uint32_t clock_freq,
              spi_mode_t mode, spi_bit_order_t bit_order,
              spi_bus_width_t bus_width)
{
    if (spi == NULL) {
        return false;
    }

    memset(spi, 0, sizeof(spi_t));

    spi->instance = instance;
    spi->clock_freq = clock_freq;
    spi->mode = mode;
    spi->bit_order = bit_order;
    spi->bus_width = bus_width;
    spi->slave_select.active_low = true;
    spi->slave_select.delay_us = 1;
    spi->dma_mode = SPI_DMA_OFF;
    spi->errors = SPI_ERROR_NONE;
    spi->enabled = false;
    spi->busy = false;

    spi_enable(spi, true);

    return true;
}

void spi_enable(spi_t *spi, bool enable)
{
    if (spi == NULL) {
        return;
    }

    spi->enabled = enable;
}

bool spi_set_clock(spi_t *spi, uint32_t clock_freq)
{
    if (spi == NULL) {
        return false;
    }

    spi->clock_freq = spi_round_clock(spi, clock_freq);

    return true;
}

void spi_set_slave_select(spi_t *spi, uint8_t pin, bool active_low,
                          uint32_t delay_us)
{
    if (spi == NULL) {
        return;
    }

    spi->slave_select.pin = pin;
    spi->slave_select.active_low = active_low;
    spi->slave_select.delay_us = delay_us;
}

void spi_cs_assert(spi_t *spi)
{
    if (spi == NULL) {
        return;
    }

    /* In real hardware, set GPIO pin LOW (for active-low CS) */
    spi->cs_asserted = true;

    /* Delay for setup time (required by some slaves) */
    /* In real code: use a busy-wait or timer */
    (void)spi->slave_select.delay_us;
}

void spi_cs_deassert(spi_t *spi)
{
    if (spi == NULL) {
        return;
    }

    /* In real hardware, set GPIO pin HIGH (for active-low CS) */
    spi->cs_asserted = false;
}

bool spi_write(spi_t *spi, const uint8_t *data, size_t length)
{
    if (spi == NULL || data == NULL) {
        return false;
    }

    /* SPI is full-duplex: writing also clocks in data from slave.
     * The received data is discarded (or stored in RX FIFO). */

    for (size_t i = 0; i < length; i++) {
        /* Push byte to TX FIFO */
        if (!spi_fifo_push(spi, data[i])) {
            break;
        }

        /* In real hardware, this would:
         * 1. Write byte to SPI data register
         * 2. Wait for TX complete flag
         * 3. Read received byte from SPI data register (discard)
         */
    }

    return true;
}

bool spi_read(spi_t *spi, uint8_t *buf, size_t length)
{
    if (spi == NULL || buf == NULL) {
        return false;
    }

    /* SPI read requires sending dummy bytes to generate clock.
     * All transmitted bytes are 0x00 (no effect on slave). */

    for (size_t i = 0; i < length; i++) {
        /* Push dummy byte to TX FIFO */
        if (!spi_fifo_push(spi, 0x00)) {
            break;
        }

        /* In real hardware:
         * 1. Write 0x00 to SPI data register (generates clock)
         * 2. Wait for RX complete
         * 3. Read byte from SPI data register into buf[i]
         */
    }

    return true;
}

bool spi_transfer(spi_t *spi, const uint8_t *tx_buf, uint8_t *rx_buf,
                  size_t length)
{
    if (spi == NULL) {
        return false;
    }

    /* Full-duplex SPI transfer: simultaneous read and write.
     *
     * For each byte:
     *   - If tx_buf[i] exists, transmit that byte
     *   - If rx_buf exists, receive into rx_buf[i]
     *   - Clock is generated for each byte
     *
     * This is the core SPI operation used for:
     *   - Reading sensor data
     *   - Writing to flash memory
     *   - Display controller communication
     */

    for (size_t i = 0; i < length; i++) {
        uint8_t tx_byte = (tx_buf != NULL) ? tx_buf[i] : 0x00;
        uint8_t rx_byte = 0x00;

        /* Push TX byte to FIFO */
        if (!spi_fifo_push(spi, tx_byte)) {
            break;
        }

        /* In real hardware, the SPI peripheral handles full-duplex:
         * 1. Write tx_byte to SPI data register
         * 2. Hardware shifts out tx_byte while shifting in from slave
         * 3. Wait for transfer complete
         * 4. Read rx_byte from SPI data register
         */
        (void)rx_byte;  /* Would be stored to rx_buf[i] in real code */
    }

    return true;
}

bool spi_transfer_blocking(spi_t *spi, const uint8_t *tx_buf,
                           uint8_t *rx_buf, size_t length,
                           uint32_t timeout_ms)
{
    if (spi == NULL) {
        return false;
    }

    /* Full-duplex transfer with timeout.
     *
     * In real hardware, this would:
     * 1. Assert CS
     * 2. Perform transfer
     * 3. Wait for complete flag with timeout
     * 4. Deassert CS
     */

    (void)tx_buf;
    (void)rx_buf;
    (void)length;
    (void)timeout_ms;

    return true;
}

void spi_set_dma_mode(spi_t *spi, spi_dma_mode_t mode)
{
    if (spi == NULL) {
        return;
    }

    spi->dma_mode = mode;
}

void spi_enable_irq(spi_t *spi, uint8_t irq_type, bool enable)
{
    if (spi == NULL) {
        return;
    }

    switch (irq_type) {
    case 0:
        spi->irq_tx_enabled = enable;
        break;
    case 1:
        spi->irq_rx_enabled = enable;
        break;
    case 2:
        spi->irq_error_enabled = enable;
        break;
    }
}

void spi_set_tx_callback(spi_t *spi, spi_tx_callback_t cb, void *context)
{
    if (spi == NULL) {
        return;
    }

    spi->tx_cb = cb;
    spi->tx_context = context;
}

void spi_set_rx_callback(spi_t *spi, spi_rx_callback_t cb, void *context)
{
    if (spi == NULL) {
        return;
    }

    spi->rx_cb = cb;
    spi->rx_context = context;
}

void spi_set_error_callback(spi_t *spi, spi_error_callback_t cb, void *context)
{
    if (spi == NULL) {
        return;
    }

    spi->error_cb = cb;
    spi->error_context = context;
}

void spi_clear_errors(spi_t *spi)
{
    if (spi != NULL) {
        spi->errors = SPI_ERROR_NONE;
    }
}

spi_error_t spi_get_errors(spi_t *spi)
{
    if (spi == NULL) {
        return SPI_ERROR_NONE;
    }
    return spi->errors;
}

uint32_t spi_get_actual_clock(spi_t *spi)
{
    if (spi == NULL) {
        return 0;
    }
    return spi->clock_freq;
}

void spi_rx_byte(spi_t *spi, uint8_t byte)
{
    if (spi == NULL) {
        return;
    }

    /* Called from RX interrupt handler.
     * Push received byte to RX FIFO. */

    if (spi->rx_count >= sizeof(spi->rx_fifo)) {
        spi->errors |= SPI_ERROR_OVERFLOW;
        if (spi->error_cb) {
            spi->error_cb(spi->error_context, SPI_ERROR_OVERFLOW);
        }
        return;
    }

    spi->rx_fifo[spi->rx_head] = byte;
    spi->rx_head = (spi->rx_head + 1) % sizeof(spi->rx_fifo);
    spi->rx_count++;

    if (spi->rx_cb) {
        spi->rx_cb(spi->rx_context, &byte, 1);
    }
}

void spi_tx_byte_done(spi_t *spi)
{
    if (spi == NULL) {
        return;
    }

    /* Called from TX interrupt handler.
     * Check if TX FIFO is empty (transfer complete). */

    if (spi->tx_count > 0) {
        spi->busy = true;
    } else {
        spi->busy = false;
        if (spi->tx_cb) {
            spi->tx_cb(spi->tx_context);
        }
    }
}
